name: Generate PDF Docs
on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Install Prince
        run: |
          curl https://www.princexml.com/download/prince-14.2-linux-generic-x86_64.tar.gz -O
          tar zxf prince-14.2-linux-generic-x86_64.tar.gz
          cd prince-14.2-linux-generic-x86_64
          yes "" | sudo ./install.sh
      - name: Build English PDF
        run: npx docusaurus-prince-pdf -u https://mjanez.github.io/ckan-docs/intro -o static/pdf/CKAN_Docs.pdf
      - name: Build Spanish PDF
        run: npx docusaurus-prince-pdf -u https://mjanez.github.io/ckan-docs/es/intro -o static/pdf/CKAN_Docs_es.pdf
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: |
            static/pdf/CKAN_Docs.pdf
            static/pdf/CKAN_Docs_es.pdf
          if-no-files-found: error
      - name: Commit PDFs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update PDF Docs" -a || echo "No changes to commit"
          git push