name: Generate PDF Docs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Generate PDF
        run: npx docs-to-pdf --initialDocURLs="https://kumarvivek1752.github.io/ckan-docs/docs/intro" --contentSelector="article" --paginationSelector="a.pagination-nav__link.pagination-nav__link--next" --excludeSelectors=".margin-vert--xl a,[class^='tocCollapsible'],.breadcrumbs,.theme-edit-this-page" --coverImage="https://api.ogptoolbox.org/images/7f/5d9cd03d8696c29670d698a93f47e3.png" --coverTitle="CKAN Docs" --outputPDFFilename="static/pdf/CKAN_Docs.pdf"
      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update PDF Docs" -a || echo "No changes to commit"
          git push
